.TH hsh 1 "December 2023" "1.0" "Simple Shell Manual"

.SH NAME
Simple Shell (hsh)

.SH SYNOPSIS
.TP
.B Interactive mode
run ./hsh then [command] [argument]

.TP
.B Non-interactive mode
echo "[command] [argument]" | ./hsh

.SH COMPILATION
gcc -Wall -Werror -Wextra -pedantic -std=gnu89 *.c -o hsh

.SH DESCRIPTION
This manual page documents the simple shell program implemented in C. It provides basic functionality such as executing commands and navigating directories.
.P
The shell supports both interactive and non-interactive modes. In interactive mode, users can type commands directly into the shell. In non-interactive mode, the shell reads commands from a file or a string.

.SH EXAMPLES
.B Interactive mode:
.EX
$ ./hsh
♥ ls
README.md     parseLine.c     readLine.c      shell.h
♥ pwd
/Users/username/hsh
♥ exit
$

.B Non-interactive mode:
.EX
$ echo "/bin/ls" | ./hsh
README.md     parseLine.c     readLine.c      shell.h
$

.SH BASIC NATIVE COMMANDS
The shell supports the following basic commands; here is a list of the most commonly used ones:
.TP
.B ls
List files and directories in the current directory.

.TP
.B pwd
Print the current working directory.

.TP
.B mv
Move or rename files or directories.

.TP
.B rm
Remove files or directories.

.TP
.B mkdir
Create a new directory.

.TP
.B rmdir
Remove an empty directory.

.TP
.B cat
Concatenate and display the content of files.

.TP
.B more / less
Display the contents of a file one screen at a time.

.TP
.B touch
Create an empty file or update the access and modification times of a file.

.SH OPTIONS
The Simple Shell program accepts options for native commands. For example, you can use options with commands like `ls`, `cp`, `mv`, and others. Below are examples:

.TP
.B ls -la
List files and directories in long format with hidden files.

.TP
.B ls -ld
List information about the current directory itself, not its contents.

.SH BUILT-IN COMMANDS
The shell supports the following built-in commands:

.TP
.B cd
Change the current directory.

.TP
.B env
Print the environment.

.SH EXITING THE PROGRAM
To exit the simple_shell program, you can use the built-in command `exit`. Enter the following command:

.TP
.B exit
Exit the shell.

Additionally, you can use keyboard shortcuts to exit the program:

.TP
.B CTRL+D
Pressing CTRL+D at the command prompt will signal the end-of-file (EOF) and terminate the shell.

.TP
.B CTRL+C
Pressing CTRL+C sends an interrupt signal to the shell, terminating the currently running command or script.

.SH AUTHOR
Anas & Léa (C22)